import type { Bonus } from "@/lib/types";

/** Catalogo demo — specchio del seed in supabase_schema.sql. */
export const DEMO_BONUSES: Bonus[] = [
  {
    id: "demo-assegno-unico",
    title: "Assegno Unico e Universale per i figli",
    authority: "INPS",
    category: "famiglia",
    amount: "da 57 € a 201 € al mese per figlio",
    deadline: "domanda sempre aperta",
    summary:
      "Sostegno economico mensile per ogni figlio a carico fino a 21 anni. L'importo varia in base all'ISEE del nucleo.",
    requirements: ["Figli a carico minori di 21 anni", "Residenza in Italia"],
    required_documents: ["Documento d'identità", "Codici fiscali dei figli", "IBAN"],
    source_url: "https://www.inps.it",
    source_name: "INPS",
    eligibility: "unknown",
    eligibility_reason: "",
    discovered_at: "2026-01-15T09:00:00Z",
    is_new: false,
  },
  {
    id: "demo-asilo-nido",
    title: "Bonus Asilo Nido",
    authority: "INPS",
    category: "famiglia",
    amount: "fino a 3.600 € annui",
    deadline: "31/12/2026",
    summary: "Rimborso delle rette di asili nido pubblici e privati o supporto domiciliare per bambini sotto i 3 anni.",
    requirements: ["Figli di età inferiore a 3 anni", "Iscrizione ad asilo nido"],
    required_documents: ["Ricevute di pagamento rette", "ISEE minorenni", "IBAN"],
    source_url: "https://www.inps.it",
    source_name: "INPS",
    eligibility: "unknown",
    eligibility_reason: "",
    discovered_at: "2026-01-15T09:00:00Z",
    is_new: false,
  },
  {
    id: "demo-psicologo",
    title: "Bonus Psicologo",
    authority: "INPS",
    category: "salute",
    amount: "fino a 1.500 €",
    deadline: "finestra annuale INPS",
    summary: "Contributo per sessioni di psicoterapia presso professionisti iscritti all'albo.",
    requirements: ["ISEE non superiore a 50.000 €", "Residenza in Italia"],
    required_documents: ["ISEE", "SPID/CIE"],
    source_url: "https://www.inps.it",
    source_name: "INPS",
    eligibility: "unknown",
    eligibility_reason: "",
    discovered_at: "2026-01-15T09:00:00Z",
    is_new: false,
  },
  {
    id: "demo-ristrutturazioni",
    title: "Bonus Ristrutturazioni (detrazione 50%/36%)",
    authority: "Agenzia delle Entrate",
    category: "casa",
    amount: "detrazione fino al 50% su max 96.000 €",
    deadline: "31/12/2026",
    summary: "Detrazione IRPEF per interventi di recupero edilizio sull'abitazione principale, ripartita in 10 anni.",
    requirements: ["Proprietario o titolare di diritto reale", "Pagamento con bonifico parlante"],
    required_documents: ["Fatture", "Bonifici parlanti"],
    source_url: "https://www.agenziaentrate.gov.it",
    source_name: "Agenzia delle Entrate",
    eligibility: "unknown",
    eligibility_reason: "",
    discovered_at: "2026-01-15T09:00:00Z",
    is_new: false,
  },
  {
    id: "demo-affitto-giovani",
    title: "Contributo Affitto Giovani (detrazione under 31)",
    authority: "Agenzia delle Entrate",
    category: "casa",
    amount: "da 991,60 € a 2.000 € annui",
    deadline: "in dichiarazione dei redditi",
    summary: "Detrazione per giovani tra 20 e 31 anni che affittano l'abitazione principale.",
    requirements: ["Età tra 20 e 31 anni", "Reddito fino a 15.493,71 €", "Contratto registrato"],
    required_documents: ["Contratto di locazione registrato"],
    source_url: "https://www.agenziaentrate.gov.it",
    source_name: "Agenzia delle Entrate",
    eligibility: "unknown",
    eligibility_reason: "",
    discovered_at: "2026-01-10T09:00:00Z",
    is_new: false,
  },
];
